version: '3.8'

services:
  app:
    build: ./opti_assist
    container_name: opti_assist_app
    ports:
      - "8000:80"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/asset_db
    depends_on:
      - db
    volumes:
      - ./opti_assist/app:/code/app

  db:
    image: postgres:15
    container_name: opti_assist_db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=asset_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
